INSERT INTO Product (product_id, name, description, price, image_path, in_stock)
VALUES
  (1, '38 Pound Bond', 'some description', 100, '/images/38_pound_bond.png',100),
  (2, '40 Pound Letter Stock', 'some description', 200, '/images/40_pound_letter_stock.png', 50),
  (3, '65 Pound Cover Stock', 'The heaviest paper that will still feed smoothly through your desktop printer.', 300, '/images/65_pound_cover_stock.png',75),
  (4, 'Airstream Deluxe A4', 'The Cadillac of paper', 500, '/images/airstream_deluxe_a4.png', 600),
  (5, 'High Quality 28 Pound Bond', 'some description', 250, '/images/high_quality_28_pound_bond.png', 1000),
  (6, 'Premium Copy Paper', 'some description', 450, '/images/premium_copy_paper.png', 75),
  (7, 'Ultra-White Cardstock', 'some description', 450, '/images/ultra_white_cardstock.png',90),
  (8, 'Sabre Pyramid', 'some description', 5000, '/images/sabre_pyramid.png', 85),
  (9, 'Sticky Quips', 'some description', 50, '/images/sticky_quips.jpg',75),
  (10, 'Two Hole Punch Letter', 'some description', 75, '/images/generic_paper.png', 255),
  (11, 'Colored Printer Paper', 'some description', 150, '/images/generic_paper.png', 277),
  (12, 'Recycled Copy Paper', 'some description', 200, '/images/generic_paper.png', 354),
  (13, 'Legal Size Paper', 'some description', 300, '/images/generic_paper.png', 456),
  (14, 'Photo Paper', 'some description', 250, '/images/generic_paper.png', 248),
  (15, 'Cardboard Sheets', 'some description', 400, '/images/generic_paper.png', 945),
  (16, 'Transparency Film', 'some description', 350, '/images/generic_paper.png', 245),
  (17, 'Laminating Pouches', 'some description', 500, '/images/generic_paper.png', 645),
  (18, 'Graph Paper', 'some description', 100, '/images/generic_paper.png', 789),
  (19, 'Notebook Paper', 'some description', 150, '/images/generic_paper.png', 548),
  (20, 'Construction Paper', 'some description', 200, '/images/generic_paper.png', 185),
  (21, 'Copy Paper', 'some description', 100, '/images/generic_paper.png', 500),
  (22, 'Printer Paper', 'some description', 200, '/images/generic_paper.png', 300),
  (23, 'Writing Paper', 'some description', 150, '/images/generic_paper.png', 400),
  (24, 'Drawing Paper', 'some description', 250, '/images/generic_paper.png', 200),
  (25, 'Craft Paper', 'some description', 300, '/images/generic_paper.png', 150),
  (26, 'Watercolor Paper', 'some description', 350, '/images/generic_paper.png', 100),
  (27, 'Sketch Paper', 'some description', 200, '/images/generic_paper.png', 250),
  (28, 'Tracing Paper', 'some description', 150, '/images/generic_paper.png', 350),
  (29, 'Origami Paper', 'some description', 100, '/images/generic_paper.png', 450),
  (30, 'Scrapbooking Paper', 'some description', 250, '/images/generic_paper.png', 200),
  (31, 'Construction Paper Pack', 'some description', 300, '/images/generic_paper.png', 150),
  (32, 'Notebook Paper Pack', 'some description', 200, '/images/generic_paper.png', 250),
  (33, 'Graph Paper Pack', 'some description', 150, '/images/generic_paper.png', 350),
  (34, 'Cardstock Paper Pack', 'some description', 100, '/images/generic_paper.png', 450),
  (35, 'Craft Paper Pack', 'some description', 250, '/images/generic_paper.png', 200),
  (36, 'Watercolor Paper Pack', 'some description', 300, '/images/generic_paper.png', 150),
  (37, 'Sketch Paper Pack', 'some description', 200, '/images/generic_paper.png', 250),
  (38, 'Tracing Paper Pack', 'some description', 150, '/images/generic_paper.png', 350),
  (39, 'Origami Paper Pack', 'some description', 100, '/images/generic_paper.png', 450),
  (40, 'Scrapbooking Paper Pack', 'some description', 250, '/images/generic_paper.png', 200),
  (41, 'Copy Paper Bundle', 'some description', 300, '/images/generic_paper.png', 150),
  (42, 'Printer Paper Bundle', 'some description', 200, '/images/generic_paper.png', 250),
  (43, 'Writing Paper Bundle', 'some description', 150, '/images/generic_paper.png', 350),
  (44, 'Drawing Paper Bundle', 'some description', 250, '/images/generic_paper.png', 200),
  (45, 'Craft Paper Bundle', 'some description', 300, '/images/generic_paper.png', 150),
  (46, 'Watercolor Paper Bundle', 'some description', 350, '/images/generic_paper.png', 100),
  (47, 'Sketch Paper Bundle', 'some description', 200, '/images/generic_paper.png', 250),
  (48, 'Tracing Paper Bundle', 'some description', 150, '/images/generic_paper.png', 350),
  (49, 'Origami Paper Bundle', 'some description', 100, '/images/generic_paper.png', 450),
  (50, 'Scrapbooking Paper Bundle', 'some description', 250, '/images/generic_paper.png', 200);

