services:
  db:
    image: mysql:latest
    container_name: db
    env_file:
      - .db
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./my-db:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/init_a.sql
      - ./data.sql:/docker-entrypoint-initdb.d/init_b.sql
      - ./test.sql:/docker-entrypoint-initdb.d/init_c.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppass"]
      interval: 5s
      timeout: 5s
      retries: 20
  
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - PYTHONPATH=/code
    expose:
      - "5000"
    ports:
      - "5000:5000"
    volumes:
      - ./app/flaskr/static:/static